# Generated by Django 5.0.4 on 2024-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
